x = "maisarah"
print(x.upper())

def mai():
    print("maisarah_tomei")
mai()

def excle(x):
    print(x + "!")
excle("cicakman")

def p_d(x):
    print(x * 2)
p_d(5)

def sq_twice(x):
    print(x**2)
sq_twice(6)

def over_lower_test(x,y):
    if x > y:
        print("over")
    elif x < y:
        print("lower")
    elif x == y:
        print("no result") 

def add(x,y):
    print(x+y)
add(5,6)

def shout(word):
    print(word + "!")
shout("nice")

def add(x,y):
    print(x+y)

def do_thrice(add,x,y):
    print(add(x,y)*3)

do_thrice(add,2,3) 

for i in range(3):
    print("mai")



